version: '3'

services: 
  app:
    build: ./docker
    entrypoint: python manage.py
    command: runserver 0.0.0.0:8080
    volumes: 
      - ./:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 8080:8080