# Generated by Django 3.2.6 on 2021-08-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210828_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='menushow',
            name='menu_kkal',
            field=models.CharField(default='0', max_length=100, null=True, verbose_name='Пищевая ценность Ккал'),
        ),
    ]
